"""add shipment actuals table

Revision ID: 748cfb09ce04
Revises: bc6e9392e1e8
Create Date: 2026-01-16 01:11:26.701336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748cfb09ce04'
down_revision: Union[str, Sequence[str], None] = 'bc6e9392e1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_actuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_actuals_id'), 'shipment_actuals', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_actuals_record_date'), 'shipment_actuals', ['record_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_actuals_record_date'), table_name='shipment_actuals')
    op.drop_index(op.f('ix_shipment_actuals_id'), table_name='shipment_actuals')
    op.drop_table('shipment_actuals')
    # ### end Alembic commands ###
