"""initial migration

Revision ID: a56a297cc67f
Revises: 
Create Date: 2026-02-16 05:18:31.968061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a56a297cc67f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_pred',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('pred_series', postgresql.ARRAY(sa.Numeric(precision=10, scale=2)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('array_length(pred_series, 1) = 14', name='ck_shipment_pred_series_len_14'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_pred_id'), 'shipment_pred', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_pred_run_date'), 'shipment_pred', ['run_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_pred_run_date'), table_name='shipment_pred')
    op.drop_index(op.f('ix_shipment_pred_id'), table_name='shipment_pred')
    op.drop_table('shipment_pred')
    # ### end Alembic commands ###
